
# small subset of survey-ccds-dr5.kd.fits for testing
survey-ccds-dr5-0.0-0.5-0.0-0.5.fits :
	curl -L -o survey-ccds-dr5-0.0-0.5-0.0-0.5.fits http://portal.nersc.gov/project/dasrepo/celeste/survey-ccds-dr5-0.0-0.5-0.0-0.5.fits

# This file is 303MB. This is because a single DECam file contains 62
# CCDs.  We need to create some smaller files for testing; ones with
# just a few CCDs.  But I'm leaving this here for now as a record of
# how to access the calibrated files.
calibrated/000/0001p000/c4d_121020_014450_oki_g_a1.fits.fz :
	curl -L --create-dirs -o calibrated/000/0001p000/c4d_121020_014450_oki_g_a1.fits.fz ftp://archive.noao.edu/public/hlsp/ls/dr5/calibrated/000/0001p000/c4d_121020_014450_oki_g_a1.fits.fz
